# This job is to test different npm profiles in master branch against Pull Request raised
# This workflow targets mocha

name: Mocha SDK Test workflow for Node on comment RUN_TESTS

on:
  issue_comment:
    branches: [ master ]
    types: [ created ]

jobs:
  comment-run:
    if: always() && github.event.issue.pull_request && contains(github.event.comment.body, 'RUN_TESTS')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        node: [ 14, 16, 18 ]
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    name: MochaJS Repo ${{ matrix.node }} - ${{ matrix.os }} Sample
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        id: check-membership
        with:
          github-token: ${{ secrets.BROWSERSTACK_TOKEN }}
          script: |
            const creator = context.payload.sender.login
            const result = await github.rest.teams.getMembershipForUserInOrg({
              org: context.repo.owner,
              team_slug: 'asi-devs',
              username: creator
            }).catch((err) => ({status: err.status, response: err.response}));
            console.log(`The comment creator ${creator} membership Status : ${result.status} Response : ${JSON.stringify(result.response)}`)
            if (result.status !== 200) {
              core.setFailed('User is not part of the owner team!')
            }

      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Setup environment for testing
        run: npm install

      - name: Run sample tests 
        run: npm run sample-test

      - name: Run local tests
        run: npm run sample-local-test
